[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"

[build]
  base = "front-end"
  publish = "dist"
  command = "npx npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
