// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/GitHub/SearchHistory copy.vue')['default']
    GitHubSearch: typeof import('./src/components/GitHub/Search.vue')['default']
    GitHubSearchHistory: typeof import('./src/components/GitHub/SearchHistory.vue')['default']
    GitHubSearchResults: typeof import('./src/components/GitHub/SearchResults.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}
