// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    GitHubSearchHistory: typeof import('./src/components/GitHub/SearchHistory.vue')['default']
    GitHubSearchInput: typeof import('./src/components/GitHub/SearchInput.vue')['default']
    GitHubSearchResults: typeof import('./src/components/GitHub/SearchResults.vue')['default']
    LayoutHeader: typeof import('./src/components/Layout/Header.vue')['default']
    LayoutSidebar: typeof import('./src/components/Layout/Sidebar.vue')['default']
  }
}
